<?php
/**
 * ForHomeAndMore Theme - Custom CSS Inclusion
 *
 * @category  ForHomeAndMore
 * @package   ForHomeAndMore_Theme
 * @author    ForHomeAndMore
 * @copyright Copyright (c) 2026 ForHomeAndMore
 *
 * @var $block \Magento\Framework\View\Element\Template
 */
?>

<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('css/styles/variables.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('css/styles/theme.css'); ?>">
