<?php
/**
 * ForHomeAndMore Theme - Custom Header Template
 *
 * @category  ForHomeAndMore
 * @package   ForHomeAndMore_Theme
 * @author    ForHomeAndMore
 * @copyright Copyright (c) 2026 ForHomeAndMore
 *
 * @var $block \Magento\Framework\View\Element\Template
 */
?>

<header class="page-header">
    <div class="header content">
        <?php echo $block->getChildHtml('header_inner'); ?>
    </div>
</header>
